// Mock data cho tours với thông tin đầy đủ
export const allToursData = [
  {
    id: 1,
    name: "Khám phá Hà Nội & Vịnh Hạ Long",
    destination: "Hạ Long",
    region: "Miền Bắc",
    province: "Hà Nội",
    image: "https://images.unsplash.com/photo-1668000018482-a02acf02b22a?w=1080",
    price: 2990000,
    duration: "5 ngày 4 đêm",
    maxSlots: 12,
    rating: 4.8,
    reviews: 324,
    badge: "Best Seller",
    type: ["Du lịch văn hóa", "Thiên nhiên"],
    description: "Tour khám phá Hà Nội và Vịnh Hạ Long với trải nghiệm du thuyền sang trọng",
    highlights: ["Du thuyền 5 sao", "Phố cổ Hà Nội", "Múa rối nước"],
  },
  {
    id: 2,
    name: "Hội An Cổ Kính & Bà Nà Hills",
    destination: "Hội An",
    region: "Miền Trung",
    province: "Đà Nẵng",
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=1080",
    price: 3490000,
    duration: "4 ngày 3 đêm",
    maxSlots: 8,
    rating: 4.9,
    reviews: 256,
    badge: "Mới",
    type: ["Du lịch văn hóa", "Biển đảo"],
    description: "Khám phá phố cổ Hội An, Bà Nà Hills với Cầu Vàng nổi tiếng",
    highlights: ["Cầu Vàng", "Phố cổ Hội An", "Bãi biển Mỹ Khê"],
  },
  {
    id: 3,
    name: "Phú Quốc - Thiên Đường Biển Đảo",
    destination: "Phú Quốc",
    region: "Miền Nam",
    province: "Phú Quốc",
    image: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=1080",
    price: 3990000,
    duration: "4 ngày 3 đêm",
    maxSlots: 5,
    rating: 4.8,
    reviews: 278,
    badge: "Khuyến mãi",
    type: ["Biển đảo", "Nghỉ dưỡng"],
    description: "Nghỉ dưỡng tại đảo ngọc Phú Quốc với bãi biển đẹp nhất Việt Nam",
    highlights: ["VinWonders", "Safari", "Bãi Sao"],
    promotion: {
      discount: 20,
      code: "PHUQUOC20",
      validUntil: "2025-12-31",
      condition: "Áp dụng cho đoàn từ 4 người",
    },
  },
  {
    id: 4,
    name: "Sapa - Chinh Phục Fansipan",
    destination: "Sapa",
    region: "Miền Bắc",
    province: "Sapa",
    image: "https://images.unsplash.com/photo-1528127269322-539801943592?w=1080",
    price: 3990000,
    duration: "6 ngày 5 đêm",
    maxSlots: 15,
    rating: 4.9,
    reviews: 312,
    type: ["Núi non", "Phiêu lưu"],
    description: "Chinh phục nóc nhà Đông Dương và khám phá vùng cao Tây Bắc",
    highlights: ["Đỉnh Fansipan", "Ruộng bậc thang", "Bản Cát Cát"],
  },
  {
    id: 5,
    name: "Nha Trang - 4 Đảo & Vinpearl",
    destination: "Nha Trang",
    region: "Miền Trung",
    province: "Nha Trang",
    image: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=1080",
    price: 2490000,
    duration: "3 ngày 2 đêm",
    maxSlots: 20,
    rating: 4.7,
    reviews: 295,
    badge: "Khuyến mãi",
    type: ["Biển đảo", "Ẩm thực"],
    description: "Tour 4 đảo nổi tiếng và trải nghiệm Vinpearl Land",
    highlights: ["Tour 4 đảo", "Vinpearl Land", "Lặn biển ngắm san hô"],
    promotion: {
      discount: 15,
      code: "NHATRANG15",
      validUntil: "2025-11-30",
      condition: "Áp dụng cho booking trước 7 ngày",
    },
  },
  {
    id: 6,
    name: "Sài Gòn & Đồng bằng sông Cửu Long",
    destination: "Mỹ Tho",
    region: "Miền Nam",
    province: "TP Hồ Chí Minh",
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=1080",
    price: 2790000,
    duration: "4 ngày 3 đêm",
    maxSlots: 10,
    rating: 4.7,
    reviews: 189,
    type: ["Thành phố", "Ẩm thực"],
    description: "Khám phá Sài Gòn và miệt vườn sông nước miền Tây",
    highlights: ["Chợ nổi Cái Răng", "Địa đạo Củ Chi", "Phố đi bộ Nguyễn Huệ"],
  },
];

export const weatherSuggestions = {
  sunny: {
    icon: "☀️",
    temp: "32°C",
    condition: "Nắng đẹp",
    tours: [1, 3, 5], // Tour biển
    description: "Thời tiết hoàn hảo cho hoạt động biển",
  },
  rainy: {
    icon: "🌧️",
    temp: "24°C",
    condition: "Có mưa",
    tours: [2, 6], // Tour văn hóa, thành phố
    description: "Thích hợp khám phá văn hóa, ẩm thực",
  },
  cool: {
    icon: "⛅",
    temp: "18°C",
    condition: "Mát mẻ",
    tours: [4], // Tour núi
    description: "Lý tưởng cho tour leo núi, trekking",
  },
};

export const promotions = [
  {
    id: 1,
    title: "Giảm 20% Tour Phú Quốc",
    code: "PHUQUOC20",
    discount: 20,
    validUntil: "31/12/2025",
    condition: "Áp dụng cho đoàn từ 4 người trở lên",
    image: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=400",
    tourIds: [3],
  },
  {
    id: 2,
    title: "Flash Sale Nha Trang - Giảm 15%",
    code: "NHATRANG15",
    discount: 15,
    validUntil: "30/11/2025",
    condition: "Booking trước 7 ngày",
    image: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=400",
    tourIds: [5],
  },
  {
    id: 3,
    title: "Combo Hà Nội - Hạ Long",
    code: "COMBO10",
    discount: 10,
    validUntil: "31/01/2026",
    condition: "Đặt 2 tour trở lên",
    image: "https://images.unsplash.com/photo-1668000018482-a02acf02b22a?w=400",
    tourIds: [1],
  },
];

export const topRatedDestinations = [
  {
    name: "Hội An",
    rating: 4.9,
    reviews: 256,
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=400",
    province: "Đà Nẵng",
  },
  {
    name: "Sapa",
    rating: 4.9,
    reviews: 312,
    image: "https://images.unsplash.com/photo-1528127269322-539801943592?w=400",
    province: "Lào Cai",
  },
  {
    name: "Phú Quốc",
    rating: 4.8,
    reviews: 278,
    image: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=400",
    province: "Kiên Giang",
  },
  {
    name: "Hà Nội",
    rating: 4.8,
    reviews: 324,
    image: "https://images.unsplash.com/photo-1668000018482-a02acf02b22a?w=400",
    province: "Hà Nội",
  },
];
